version: "3.8"

services:
  pihole:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: "arm64"

    image: local/pihole:arm64
    container_name: pihole

    # Host networking fixes UDP DNS on Raspberry Pi OS Bookworm
    network_mode: host

    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: ${DNS1}
      DNS2: ${DNS2}
      SERVERIP: ${SERVERIP}

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

    cap_add:
      - NET_ADMIN

    restart: unless-stopped



